# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy ofthe MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
ntp:
 - { ntp_ip: 10.255.1.1, prefer: prefer}
 - { ntp_ip: 10.255.1.10, prefer: }

snmp:
 - { snmp_ip: <ip address> }
 
logging:
 - { logging_ip: 10.255.1.1 }
 - { logging_ip: 10.255.1.10 }
 
radius:
 - { radius_ip: <ip address> }

ssh_key:
 - { ssh_key_id: <id>, ssh_key: <key> }
...
